#!/bin/sh
ORIGIN="https://${GH_TOKEN}@github.com/Ideabile/ideabile.github.io.git";
export BASE_URL="https://ideabile.github.io/";

git config --global user.email "drone@ideabile.com"
git config --global user.name "Ideabile CI"

npm run generate
git branch -D master 2>/dev/null || true
git push --force $ORIGIN :master
git branch -D draft 2>/dev/null || true
git checkout -b draft
git add -f dist
git commit -am "Deploy on gh-pages"
git subtree split --prefix dist -b master
git push --force $ORIGIN master:master
